build:
    dependencies:
        before:
            - npm install -g mocha istanbul
    environment:
            node: '6.9'

    tests:
        override:
            - jshint-run
            -
                command : 'istanbul cover _mocha --report clover'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'

checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/