language: node_js
node_js:
  - node
  - 7
  - 6
  - 5
  - 4

env:
  - NODE_ENV=travis

before_install:
  - sudo apt-get install python make g++
  - npm install istanbul mocha coveralls codacy-coverage node-gyp -g

before_script:
  - sleep 15

script: istanbul cover _mocha --report lcovonly

after_success:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage

services:
  - mongodb

notifications:
   email:
     - flaesch.arnaud@esgi.fr